import {
  Pizza4Quesos,
  PizzaCalabresa,
  Muzzarella,
  PizzaPalmitos,
  PizzaFugazzeta,
  PizzaNapolitana,
  PizzaPanceta,
  PizzaProvolone,
  PizzaFaina,
  CocaCola,
  Sprite,
  Fanta,
  BirraOne,
  AndesRubia,
  AndesRoja,
  Stella,
  Panchy,
  Portillo,
  CarneSuave,
  CarneMalbec,
  CarnePicante,
  Humita,
  Pollo,
  Verdura,
  PancetaCiruela,
  JyQ,
  Roquefort,
  Caprese,
} from '../assets';

import Product from '../models/Product';

function getAllProducts() {
  const data = [
    {
      productId: 1,
      imagePath: Muzzarella,
      productName: 'Pizza Muzzarella',
      price: 4900,
      productDescription: 'Muzzarella',
      category: { idCategory: 1, name: 'pizza' },
    },
    {
      productId: 2,
      imagePath: Pizza4Quesos,
      productName: 'Pizza Cuatro Quesos',
      price: 5400,
      productDescription: 'Roquefort, Parmesano, Fontina y...',
      category: { idCategory: 1, name: 'pizza' },
    },
    {
      productId: 3,
      imagePath: PizzaNapolitana,
      productName: 'Pizza Napolitana',
      price: 5400,
      productDescription: 'Rodajas de tomate y albahaca',
      category: { idCategory: 1, name: 'pizza' },
    },
    {
      productId: 4,
      imagePath: PizzaFugazzeta,
      productName: 'Pizza Fugazzeta',
      price: 5600,
      productDescription: 'Cebolla y provolone gratinado',
      category: { idCategory: 1, name: 'pizza' },
    },
    {
      productId: 5,
      imagePath: PizzaCalabresa,
      productName: 'Pizza Calabresa',
      price: 5600,
      productDescription: 'Longanizas en rodajas',
      category: { idCategory: 1, name: 'pizza' },
    },
    {
      productId: 6,
      imagePath: PizzaPanceta,
      productName: 'Pizza Panceta',
      price: 6200,
      productDescription: 'Muzarella, panceta y huevo',
      category: { idCategory: 1, name: 'pizza' },
    },
    {
      productId: 7,
      imagePath: PizzaProvolone,
      productName: 'Pizza Provolone',
      price: 5900,
      productDescription: 'Provolone con aceitunas negras',
      category: { idCategory: 1, name: 'pizza' },
    },
    {
      productId: 8,
      imagePath: PizzaPalmitos,
      productName: 'Pizza Palmitos',
      price: 7100,
      productDescription: 'Palmitos, salsa golf y huevo',
      category: { idCategory: 1, name: 'pizza' },
    },
    {
      productId: 9,
      imagePath: PizzaFaina,
      productName: 'Pizza Faina',
      price: 4000,
      productDescription: 'Fainá sin acompañantes',
      category: { idCategory: 1, name: 'pizza' },
    },
    {
      productId: 10,
      imagePath: CarneSuave,
      productName: 'Carne Suave',
      price: 600,
      productDescription: 'Carne molida c/ huevo',
      category: { idCategory: 2, name: 'empanada' },
    },
    {
      productId: 11,
      imagePath: CarnePicante,
      productName: 'Carne picante',
      price: 600,
      productDescription: 'Picante moderado, carne triturada',
      category: { idCategory: 2, name: 'empanada' },
    },
    {
      productId: 12,
      imagePath: CarneMalbec,
      productName: 'Carne al malbec',
      price: 700,
      productDescription: 'Carne cortada a cuchillo al malbeec',
      category: { idCategory: 2, name: 'empanada' },
    },
    {
      productId: 13,
      imagePath: JyQ,
      productName: 'Jamon y queso',
      price: 600,
      productDescription: 'Jamon en lonjas con muzzarella',
      category: { idCategory: 2, name: 'empanada' },
    },
    {
      productId: 14,
      imagePath: Roquefort,
      productName: 'Roquefort',
      price: 600,
      productDescription: 'Roquefort y jamón',
      category: { idCategory: 2, name: 'empanada' },
    },
    {
      productId: 15,
      imagePath: Caprese,
      productName: 'Capresse',
      price: 600,
      productDescription: 'Queso, tomate y albahaca',
      category: { idCategory: 2, name: 'empanada' },
    },
    {
      productId: 16,
      imagePath: Humita,
      productName: 'Humita',
      price: 600,
      productDescription: 'Salsa blanca y choclo',
      category: { idCategory: 2, name: 'empanada' },
    },
    {
      productId: 17,
      imagePath: PancetaCiruela,
      productName: 'Panceta y Ciruela',
      price: 700,
      productDescription: 'Panceta, queso y ciruela',
      category: { idCategory: 2, name: 'empanada' },
    },
    {
      productId: 18,
      imagePath: Pollo,
      productName: 'Pollo clásicas',
      price: 600,
      productDescription: 'Pollo y salsa especial de la casa',
      category: { idCategory: 2, name: 'empanada' },
    },
    {
      productId: 19,
      imagePath: Verdura,
      productName: 'Verdura',
      price: 600,
      productDescription: 'Espinaca fresca y muzzarella',
      category: { idCategory: 2, name: 'empanada' },
    },
    {
      productId: 20,
      imagePath: CocaCola,
      productName: 'Coca Cola',
      price: 1500,
      productDescription: '1.5 lts',
      category: { idCategory: 3, name: 'bebida' },
    },
    {
      productId: 21,
      imagePath: Sprite,
      productName: 'Sprite',
      price: 1500,
      productDescription: '1.5 lts',
      category: { idCategory: 3, name: 'bebida' },
    },
    {
      productId: 22,
      imagePath: Fanta,
      productName: 'Fanta',
      price: 1500,
      productDescription: '1.5 lts',
      category: { idCategory: 3, name: 'bebida' },
    },
    {
      productId: 23,
      imagePath: BirraOne,
      productName: 'Chango Beer',
      price: 2500,
      productDescription: 'Cerveza rubia con leve amargor',
      category: { idCategory: 3, name: 'bebida' },
    },
    {
      productId: 24,
      imagePath: AndesRubia,
      productName: 'Andes rubia',
      price: 3000,
      productDescription: 'Cerveza rubia de litro',
      category: { idCategory: 3, name: 'bebida' },
    },
    {
      productId: 25,
      imagePath: AndesRoja,
      productName: 'Andes Roja',
      price: 3000,
      productDescription: 'Cerveza roja de litro',
      category: { idCategory: 3, name: 'bebida' },
    },
    {
      productId: 27,
      imagePath: Stella,
      productName: 'Stella',
      price: 3500,
      productDescription: 'Stella de litro',
      category: { idCategory: 3, name: 'bebida' },
    },
    {
      productId: 28,
      imagePath: Panchy,
      productName: 'Panchy Juice',
      price: 1400,
      productDescription: 'Refresco de 330ml',
      category: { idCategory: 3, name: 'bebida' },
    },
    {
      productId: 29,
      imagePath: Portillo,
      productName: 'Vino tinto',
      price: 5100,
      productDescription: 'Vino Cabernet Suavignon',
      category: { idCategory: 3, name: 'bebida' },
    },
  ];

  // aca iria la peticion al backend con fetch o axios en vez del array este.
  // por ahora hacemos un metodo ""mockup"".

  return data.map((product) => new Product({ ...product }));
}

export default getAllProducts;
